SELECT * FROM employees ORDER BY FIRST_NAME ASC;

SELECT FIRST_NAME, LAST_NAME, SALARY, (SALARY*15/100) AS pdv15 FROM employees ORDER BY FIRST_NAME ASC;

SELECT SUM(SALARY) FROM employees;

SELECT MIN(SALARY) FROM employees;

SELECT MAX(SALARY) FROM employees;

SELECT COUNT(EMPLOYEE_ID) as employee_count, SUM(SALARY)/COUNT(EMPLOYEE_ID) as avarage FROM employees;